### ISSUE TITLE
[a]_Support_Arm_xN.stl rabbit placed 1 layer above the bed

### ISSUE THREAD

**Issue by mszulen** [Enraged-Rabbit-Community/ERCF_v2#19]
Is this intentional? There's a single layer space between beed and the rabbit figure in the Support Arm file.

<img width="714" alt="image" src="https://github.com/Enraged-Rabbit-Community/ERCF_v2/assets/6932464/c07e499b-eba1-423d-a1aa-f3170ade8df2">

![image](https://github.com/Enraged-Rabbit-Community/ERCF_v2/assets/6932464/a227ec34-cadb-4584-9f16-08f3c918693a)

**Comment by o1hitman1o** [comment]
@mszulen How are you getting bridging on the first layer. I can't see to get it only on the second layer and when I try to print it wants to fail.

**Comment by mszulen** [comment]
It does print but it's not looking good as you can see.
![2](https://github.com/Enraged-Rabbit-Community/ERCF_v2/assets/6932464/3f426c1b-5f91-4d27-87ae-f8f9dfc22f10)
![1](https://github.com/Enraged-Rabbit-Community/ERCF_v2/assets/6932464/2bb4c8b9-1fe0-4462-abc7-783d746a74a5)

**Comment by o1hitman1o** [comment]
It does appear that maybe this was a mistake, other photos on discord show it being solid on the first layer...
![IMG_6754](https://github.com/Enraged-Rabbit-Community/ERCF_v2/assets/28017580/4c536fbc-058d-430a-bb66-337b3bc0c1f2)

**Comment by mszulen** [comment]
then the file in STL folder is wrong/broken.

**Comment by o1hitman1o** [comment]
Per Terrance on Discord it is supposed to be one layer higher to give a texture to the rabbit.

**Comment by mszulen** [comment]
oh.. ok. Anyway... it won't be visible once assembled :) Not a big issue :D

**Comment by o1hitman1o** [comment]
I guess the issue can be closed then.
