### ISSUE TITLE
BOM is short on Omron microswitches

### ISSUE THREAD

**Issue by GarthSnyder** [Enraged-Rabbit-Community/ERCF_v2#2]
It looks like one microswitch is needed for each ERCT lane. The master BOM on Google Sheets leaves these out of the count.

Also, the modified toolhead may need two microswitches and two 5.5mm ball bearings if you elect to install both sensors. The spreadsheet only shows one each. I would hate for someone to order from China and discover they're one short three weeks later. 🙂

**Comment by kinematicdigit** [comment]
Thanks. The BOM has been updated for this now.
