### ISSUE TITLE
Manual: calibration tool instructions

### ISSUE THREAD

**Issue by shiftingtech** [Enraged-Rabbit-Community/ERCF_v2#25]
on page 4, the manual states

"Beware that this project requires a well tuned printer and slicing profile, as there are many press fits and plastic on plastic
mechanisms. You should first print the ERCF_Calibration_Tool.stl, test the part, as shown in the manual, tune your printer and
profile if needed, and then only print the rest of the parts"

This should mention that you actually need to print TWO parts:  one of the tests appears to be a fit test between the calibration tool, and the tophat.

(easy enough to figure out a few pages later, but I for one had already hit print before I got to the page saying how to read the thing...)

**Comment by MissileLaunchSystem** [comment]
Resolved by Commit c8028c1 updating the manual. Thanks for the help!
