### ISSUE TITLE
Manual: additional tools note

### ISSUE THREAD

**Issue by shiftingtech** [Enraged-Rabbit-Community/ERCF_v2#26]
Page 8 states

"ADDITIONAL TOOLS
We provide additional tool recommendations in
our sourcing guide. Visit https://vorondesign.com/
sourcing_guide and switch to the “Voron Tools”
tab at the bottom of the page"

This is a potential source of confusion, since ERCF has it's own sourcing guide/BOM.  I would suggest phrasing it as something like:

"ADDITIONAL TOOLS
The tools needed are similar to those used building a 
Voron. For recommendations, visit https://vorondesign.com/
sourcing_guide and switch to the “Voron Tools”
tab at the bottom of the page

**Comment by MissileLaunchSystem** [comment]
Resolved by Commit c8028c1 updating the manual. Thanks for the help!
