### ISSUE TITLE
Screws attaching parts to 2020 extrusion dig into the bottom of the slot

### ISSUE THREAD

**Issue by arkeet** [Enraged-Rabbit-Community/ERCF_v2#28]
The parts are modelled in such a way that the M3x8 screws extend 6.1mm into the slot (see first picture below), which is larger than the 6mm depth of the slot. In addition, due to compression of the part, as well as the possibility of a screw being over nominal length, the actual distance the screw goes into the slot can be even greater. In my designs I try to leave at least 1mm of space between the screw and the slot bottom (i.e. screw should extend 5mm into the slot, which means a distance from counterbore to the face that touches the surface of the extrusion should be at least 3mm for a M3x8 screw) to avoid this. A quick survey of Trident and V2 parts shows a range of 1.0-1.6mm for screw to slot bottom distance.

Affected parts (locations circled in red below):
* Gear_Box_Front (4 screws)
* End Bypass (1 screw)

![image](https://github.com/Enraged-Rabbit-Community/ERCF_v2/assets/2345921/715ce537-b2c6-493c-a99c-944fc0972ae5)
![image](https://github.com/Enraged-Rabbit-Community/ERCF_v2/assets/2345921/24689465-dbda-4c88-a371-afe6fa0900ce)
![image](https://github.com/Enraged-Rabbit-Community/ERCF_v2/assets/2345921/c71669de-dd2a-4b62-a5b5-0f3b62b8b130)

**Comment by MissileLaunchSystem** [comment]
I just merged these changes. Thanks for the help!
