### ISSUE TITLE
New easier to print [a]_BTT_MMB_Support_Arm_Endcap_Bunny_Outline.stl does not have cutouts for alignment with coupler blocks.

### ISSUE THREAD

**Issue by Ekodas** [Enraged-Rabbit-Community/ERCF_v2#32]
The new easier to print [a]_BTT_MMB_Support_Arm_Endcap_Bunny_Outline.stl does not have the 3 alignment cutouts to allow it to mate with the coupler blocks.  The old version did have these cutouts.

Also, the hole for attaching to the last [a]_Support_Arm_Mount_xN doesn't line up either.

**Comment by o1hitman1o** [comment]
- [ ] 
![Screenshot_20240101-194502](https://github.com/Enraged-Rabbit-Community/ERCF_v2/assets/28017580/f3ca76ec-dd89-4c92-8553-6180b38e54d6)
![Screenshot_20240101-194543](https://github.com/Enraged-Rabbit-Community/ERCF_v2/assets/28017580/065bca7e-49df-4a90-921b-5d229108bf98)
This is confirmed. Need to update easy to print version.

**Comment by MissileLaunchSystem** [comment]
Resolved with a commit I just pushed a minute ago. The new file is available here:
Recommended_Options/ERCT_Buffer/Stls/Support_Arm/Bunny Logo Outline (easier to print)/[a]_BTT_MMB_Support_Arm_Endcap_Bunny_Outline.stl

**Comment by theminjus** [comment]
i would reopen this one , 
[a]_Support_Arm_Endcap_No_Electronic_Box_Bunny_Outline.stl
is hole is not aligned for the endcap heat insert
