### ISSUE TITLE
Wrong link in readme files

### ISSUE THREAD

**Issue by chrsdion** [Enraged-Rabbit-Community/ERCF_v2#35]
The link to the manual is wrong in the readme. It links to a manual named ERCF_v2_Manual.pdf. The actual name is ERCF_v2 Manual.pdf

![image](https://github.com/Enraged-Rabbit-Community/ERCF_v2/assets/9884623/198f1ad1-6bb8-4167-b96a-f09e68b7c1d1)

**Comment by MissileLaunchSystem** [comment]
Fixed with latest commit. Thank you!
