### ISSUE TITLE
Add Encoder push tool to the STL's as is missing

### ISSUE THREAD

**Issue by PaulMellor** [Enraged-Rabbit-Community/ERCF_v2#40]
Had to go looking for the encoder tool, can we please add it to the Tools or the encoder section of the STL's

https://github.com/mneuhaus/EnragedRabbitProject/blob/e0272b7838a99c0ad8416ad5d3ec9c45b1973cac/usermods/Binky/STL/Tool_Encoder_SlottedWheel_PushTool.stl

**Comment by Benoitone** [comment]
it's on the [Tools folder](https://github.com/Enraged-Rabbit-Community/ERCF_v2/blob/master/Stls/Tools/Slotted_Wheel_Push_Tool.stl).
