### ISSUE TITLE
ERCFv2 Manual: page 99 inconsistent screw specified

### ISSUE THREAD

**Issue by akempster** [Enraged-Rabbit-Community/ERCF_v2#47]
Git hash: 7f9bdc8b411cc4deb2719941ea4e03b8cd38f689

What i observed
For the encoder assembly on page 99 the diagram specifies an M3x8 BHCS when the assembly text below indicates M3x8 SHCS.

What i think it should do
Either diagram or text should be updated to the correct option or the text should be updated to indicate either screw type may be used.

**Comment by recrudesce** [comment]
I don't think it matters, all it does is actuate the endstop.
