### ISSUE TITLE
[Toolhead Sensors] Add Kapton tape to BOM

### ISSUE THREAD

**Issue by tinyfluffs** [Enraged-Rabbit-Community/ERCF_v2#48]
There's a very narrow clearance between the toolhead sensor microswitches and an SB2040v2. Other toolhead PCBs are probably affected by this too.

To prevent shorting, I recommend we add a piece of kapton tape to the BOM, so people can opt to add it behind the toolhead PCB, should it be required.

![](https://github.com/Enraged-Rabbit-Community/ERCF_v2/assets/49796753/ffa37afc-7a7e-4f53-8a6c-fe238bcec479)
![](https://github.com/Enraged-Rabbit-Community/ERCF_v2/assets/49796753/538d35f9-5972-425b-9007-dc27087c567f)

**Comment by Tyler8299** [comment]
This is up to the user to decide as there are too many different boards available. I personally have not had any clearance issues using CW2 or G2E but i also use the ebb2209. 

![IMG_1842](https://github.com/Enraged-Rabbit-Community/ERCF_v2/assets/121695166/68b2a25e-16c9-4c8f-ac23-cb25ae987fe0)
