### ISSUE TITLE
ERCFv2 Manual: Page 40, Motor Arm Microfit specified for local MCU (Should be for remote)

### ISSUE THREAD

**Issue by iwm911** [Enraged-Rabbit-Community/ERCF_v2#49]
Hi,

in the manual the text specifies to use the Microfit motor mount for the local MCU setup, which is wrong by the text on page 44.
![image](https://github.com/Enraged-Rabbit-Community/ERCF_v2/assets/2302032/4361ba96-1e06-463b-9d8f-c85f8f69733f)
![image](https://github.com/Enraged-Rabbit-Community/ERCF_v2/assets/2302032/7c35697e-850e-4bff-83bf-31d6b6ecdb9f)

which one is the right one?

**Comment by MissileLaunchSystem** [comment]
Apologies for the confusion, the microfits are for use with a remote MCU. I have fixed this in the live manual file and it will be reflected the next time I push a new manual PDF. Thanks for catching that!
