### ISSUE TITLE
Integrated support is not printed correctly

### ISSUE THREAD

**Issue by mboo83** [Enraged-Rabbit-Community/ERCF_v2#61]
The support is only partially printed. Different slicers and settings show the same result. 

![Screenshot 2024-02-07 081418](https://github.com/Enraged-Rabbit-Community/ERCF_v2/assets/117382205/e54697e7-5883-404e-87a9-cbdd13dc2d7c)
![Screenshot 2024-02-07 081946](https://github.com/Enraged-Rabbit-Community/ERCF_v2/assets/117382205/f8a3ecc5-9965-4030-a3b3-80462fde3f45)

**Comment by alexstone** [comment]
I printed with Arachne wall generator and managed to get the support to print. However, without this setting, those supports straight up _do not_ print and you end up with blocks you can't really use.

I would prefer to see the block without the in-build supports, and markers in the docs of where to add them. This would allow the use of interface materials for cleaner bottom surfaces.

**Comment by mboo83** [comment]
Thank you, i will give it a Try. You can export it from the CAD Version with Fusion 360 and remove the Support. I printed the one that comes with the Thumper Blocks Mod. That did came out perfect with the integrated Support.

**Comment by MissileLaunchSystem** [comment]
I've added support-less versions of the Filament_Path, Tophat, and Base under the sub-folder "No_Supports."
