### ISSUE TITLE
Suggest adding more clearance to the gear box to route motor wires through

### ISSUE THREAD

**Issue by alexstone** [Enraged-Rabbit-Community/ERCF_v2#64]
I wanted to replace my NEMA14 with a NEMA17. When trying to remove the NEMA14, I found that I actually had to disassemble the _entire_ ERCF to get the cable out without snipping it and re-doing the housing. An extra few millimeters here would really help with maintenance.

![IMG_1284](https://github.com/Enraged-Rabbit-Community/ERCF_v2/assets/331943/005c7c00-f264-401f-8c0a-c02162362c60)

**Comment by mboo83** [comment]
I did the same Mistake. You can easyly pinout the Cables and pull them through the Hole.

**Comment by MissileLaunchSystem** [comment]
I've merged Ark's changes that add more space to the wiring path. This is as fixed as it is going to get until we redesign the gearbox.
