### ISSUE TITLE
Match Selector Parts for Matched Material Shrinkage

### ISSUE THREAD

**Issue by Tuckpolo** [Enraged-Rabbit-Community/ERCF_v2#74]
Ideally you have your filament dialed in, but to improve build Selector Cart, Linear Axis Idler Block, and Linear Axis Selector Motor Support  should all be made from the same material. I would propose changing them all to the accent color.

**Comment by MissileLaunchSystem** [comment]
If your ABS is inconsistently shrinking between colors, you need better ABS. This has been debated extensively on Discord, so apologies for the short answer.
