### ISSUE TITLE
MMB Can 1.1 does not fit

### ISSUE THREAD

**Issue by TravisWilder** [Enraged-Rabbit-Community/ERCF_v2#83]
Hello
the new MBB Can 1.1 does not fit in the case [a]_BTT_MMB_Box_Lid.stl / [a]_BTT_MMB_Support_Arm_Endcap.stl

kind regards

**Comment by o1hitman1o** [comment]
@TravisWilder I curious where are you finding the spects for MMB CAN V1.1? I can't seem to find anything on it.

**Comment by TravisWilder** [comment]
I checked the STL which shows 125,448 * 54,4 ... could it be material shrinking?

**Comment by TravisWilder** [comment]
I printed again .. now it fits - sorry

**Comment by Luoti** [comment]
@TravisWilder What did you do differently the second time, because I'm having the same problem. I already made it work with a chisel though! 😅
