### ISSUE TITLE
Slicer Settings to print the parts

### ISSUE THREAD

**Issue by dushyantahuja** [Enraged-Rabbit-Community/ERCF_v2#93]
I simply cannot find the recommended slicer settings and material for the printed parts. Can you please point me in the right direction and update the documentation please.

**Comment by ningpj** [comment]
ABS. You will find a summary of print settings on pg 4 of the manual. https://github.com/Enraged-Rabbit-Community/ERCF_v2/blob/master/Documentation/ERCF_v2_Manual.pdf

**Comment by dushyantahuja** [comment]
Thanks - I swear I read the manual :-)

**Comment by ningpj** [comment]
No problem. Easy to overlook.
